---
- name: Ensure MariaDB-server is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure mariadb is enabled and started
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started

- name: Ensure PyMySQL is installed for Ansible MySQL modules
  ansible.builtin.package:
    name: python3-PyMySQL
    state: present

- name: Create a database named webappdb
  community.mysql.mysql_db:
    name: webappdb
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create a database user for the web application
  community.mysql.mysql_user:
    name: webappuser
    password: "{{ db_password }}"
    priv: 'webappdb.*:ALL'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

