---
- name: Copy .md files to deploy's home directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/deploy/"
    owner: deploy
    group: deploy
    mode: '0644'
  with_fileglob:
    - "files/*.md"
