---
- name: Ensure MariaDB is installed and running
  hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure mariadb is enabled at boot
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started
