---
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Ensure nginx is started at boot
  ansible.builtin.service:
    name: nginx
    enabled: true      # startar nginx automatiskt vid boot
    state: started     # startar nginx direkt
